server:
  port: 8095

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: sml

#  datasource:
#    url: jdbc:mysql://localhost:3306/smldb
#    username: root
#    password: 1234
#    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
#  h2:
#    console:
#      enabled: true
#      path: /h2
