server:
  port: 8095

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongoDemo
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
