server:
  port: 8093

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 1234



management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost